### ISSUE TITLE
Normalize hex codes in data.json

### ISSUE THREAD

**Issue by bsoyka** [saviomartin/gradientking#16]
**Is your feature request related to a problem? Please describe.**
This isn't so much a problem as it is a visual change that should occur. Some of the hex codes in [`data.json`](https://github.com/saviomartin/gradientking/blob/main/public/data.json) have lowercase characters that end up appearing that way on the gradient page.

**Describe the solution you'd like**
I'd like to capitalize all hex codes in [`data.json`](https://github.com/saviomartin/gradientking/blob/main/public/data.json) so they are all the same format.

**Describe alternatives you've considered**
This doesn't have to be done as it's just a minor visual change, so it could simply be ignored.

Another alternative would be to normalize the hex codes when rendering the gradient pages rather than editing the data itself.

**Comment by saviomartin** [comment]
Ok, I have assigned you to this. Go work on this!
