### ISSUE TITLE
Hide Packages

### ISSUE THREAD

**Issue by verma-kunal** [saviomartin/gradientking#23]
Suggested to hide packages if not being used in the repo.

Screenshot
![Screenshot 2021-05-28 at 2 58 32 PM](https://user-images.githubusercontent.com/72245772/119962946-2c710900-bfc5-11eb-8840-19b84c97b115.png)

**Comment by saviomartin** [comment]
Thanks, everything is now perfect!

**Comment by verma-kunal** [comment]
Awesome !! Happy to hear that👍
