### ISSUE TITLE
Image/Link Issues In Readme

### ISSUE THREAD

**Issue by verma-kunal** [saviomartin/gradientking#24]
At some places in the `readme.md` file, images/links are not rendered properly!

Screenshots:
![Screenshot 2021-05-28 at 3 00 37 PM](https://user-images.githubusercontent.com/72245772/119963221-778b1c00-bfc5-11eb-9591-4ff56f054cc4.png)
![Screenshot 2021-05-28 at 3 01 15 PM](https://user-images.githubusercontent.com/72245772/119963291-8e317300-bfc5-11eb-81ff-41e3b656938b.png)

**Comment by saviomartin** [comment]
Solved everything! Thanks for letting me know!

**Comment by verma-kunal** [comment]
Awesome! Happy to hear that👍
