### ISSUE TITLE
Unable to access https://gradient-king.vercel.app/

### ISSUE THREAD

**Issue by nikiljos** [saviomartin/gradientking#31]
![image](https://user-images.githubusercontent.com/57913645/135428769-c38a18bf-97c3-4d52-837d-446e3338c0e3.png)

To reproduce
- Open https://gradient-king.vercel.app/ in an incognito window

**Comment by petercr** [comment]
Yeah I had the exact same problem.
Let me know if I can help 👍🏻

**Comment by Prashoon123** [comment]
This issue is fixed, I guess! 
![image](https://user-images.githubusercontent.com/64588766/138437345-7dc89c47-c704-4a02-92ab-f18e0496029e.png)

**Comment by nikiljos** [comment]
> This issue is fixed, I guess! ![image](https://user-images.githubusercontent.com/64588766/138437345-7dc89c47-c704-4a02-92ab-f18e0496029e.png)

Yes it is fixed... Thank you @saviomartin
