### ISSUE TITLE
Numeric ID conflicts

### ISSUE THREAD

**Issue by andaviaco** [saviomartin/gradientking#4]
**Is your feature request related to a problem? Please describe.**
While looking into the opened PRs as a reference to create my own, I noticed the data items have a numeric ID that might cause conflicts. 

When we want to contribute with new gradients, we have to look at the latest ID and manually set the item's ID to the next value. I think this is a conflict-prone mechanism for the IDs:
- It is hard to keep track of the latest ID if the array is constantly changing.
- When new data is merged, authors of opened PRs must change their gradient's ID to avoid conflicts.
- Duplicated IDs cause unexpected behaviors, like getting redirected to a different grading when clicking a gradient with a duplicated ID.
- For maintainers and reviewers, it could be time-consuming to verify the new gradients are using the correct IDs.

**Describe the solution you'd like**
Probably the simplest solution is to use name-like string IDs. 

Example: 
``` json
[
  {
    "id": "black-and-white",
    "githubUsername": "andaviaco",
    "colors": [
      "#000000",
      "#ffffff"
    ]
  }
]
```
Pros:
- It is easier to come up with unique IDs -> less likely to have conflicts.
- We can use human-friendly IDs.
- We can prefix/suffix the IDs to increase the uniqueness.

Cons:
- Contributors still have to set the ID and make sure it is unique.
- Reviewers still have to make sure the new gradients have unique IDs.
- String IDs have to be "URL friendly".

**Describe alternatives you've considered**
We can also explore automatic ID generation solutions.

**Additional context**
PRs #2 and #3 are using the same IDs for their gradients. Once one of them is merged, the other PR has to be updated to change the IDs.

**Comment by saviomartin** [comment]
Hello there 👋

What you said is exactly correct. I'm having conflicted PRs. So, I'm now resolving it, and only after resolving I'm merging that.
I know that this is work, So, I'm gonna build auto-id generation in this. If you would love, feel free to work on this @andaviaco

Hope it helps, thanks
Savio Martin, developer

**Comment by saviomartin** [comment]
Everything becomes much easier, removed the option for id. Now, just use this, v2 is here ✌️

```json
[
  {
    "colors": [
      "#000000",
      "#ffffff"
    ]
  }
]
```
