### ISSUE TITLE
No Visual feedback when selecting text within the textarea

### ISSUE THREAD

**Issue by shah62** [saviomartin/gradientking#7]
**Describe the bug**
On the gradient page `/gradient/:id` while trying to select the textarea code block, there wasn't a background which indicated that I was actually selecting something within the block.

**To Reproduce**

1. Go to home page and select any gradient
2. Try and select some portion of the text within the codeblock

**Expected behavior**
I think it should show a background rather than being transparent.

**Context**
I first encountered this issue when I was trying to copy a part of the code since I was trying to use it in a CSSInJS project where the copying the traditional CSS won't work. I went through the source code and saw that the `::selection` was intentionally being set with a background property of transparent. I could open a PR addressing these comments if needed.

**Comment by saviomartin** [comment]
![scrnli_02_03_2021_11-11-16](https://user-images.githubusercontent.com/61895712/109603606-09f75d00-7b48-11eb-9c8d-12df8a72b957.png)

Solved the issue, thanks for letting me know! 💖
