### ISSUE TITLE
Automatic theme detection

### ISSUE THREAD

**Issue by shah62** [saviomartin/gradientking#9]
**Is your feature request related to a problem? Please describe.**
Would it be nice to have automatic color palette detection of the device using the app?

**Describe the solution you'd like**
Using the Material UI's `useMediaQuery` hook we can listen to the `(prefers-color-scheme: dark)` media query property and set our dark state accordingly.

**Additional context**
Instead of defaulting to false for the dark state we could check what someone has set on their device and listen to those changes. 

A snapshot of the changes.
https://user-images.githubusercontent.com/52537686/109578636-87c65480-7ac5-11eb-953b-fb123e166e48.mov

A PR including the changes on my forked version: https://github.com/shah62/gradientking/pull/1.

I could open the same PR to be merged into master here. Keep up the nice work!

**Comment by saviomartin** [comment]
Looks great 🤟, thanks. Give a PR. I would be happy to merge this 🚀
